# Generated by Django 5.1.2 on 2025-03-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MEDECIN', 'Médecin'), ('PATIENT', 'Patient'), ('RADIOLOGUE', 'Radiologue'), ('LABORANTIN', 'Laborantin'), ('PRATICIEN', 'Praticien de santé')], default='PATIENT', max_length=15),
        ),
    ]
