# Generated by Django 5.1.7 on 2025-03-21 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=5)),
                ('medical_condition', models.CharField(max_length=100)),
                ('date_of_admission', models.DateField()),
                ('doctor', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('insurance_provider', models.CharField(max_length=100)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_number', models.IntegerField()),
                ('admission_type', models.CharField(max_length=50)),
                ('discharge_date', models.DateField()),
                ('medication', models.CharField(max_length=100)),
                ('test_results', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
