# Generated by Django 5.1.7 on 2025-03-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_laborantin_medecin_patient_medicalrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='laborantin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='radiologue',
            name='user',
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Laborantin',
        ),
        migrations.DeleteModel(
            name='Medecin',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Radiologue',
        ),
    ]
