# Generated by Django 5.1.7 on 2025-03-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_abekey_laborantin_medecin_patient_medicalrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='insurance_policy',
            new_name='abe_policy',
        ),
    ]
