# Generated by Django 5.1.7 on 2025-03-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_insurance_policy_patient_abe_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='abe_policy',
            field=models.TextField(blank=True),
        ),
    ]
