# Generated by Django 5.1.7 on 2025-03-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_consultation_date_alter_patient_abe_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='encrypted_insurance',
            field=models.CharField(max_length=15),
        ),
    ]
