# Generated by Django 5.1.7 on 2025-03-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_patient_encrypted_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='encrypted_insurance',
            field=models.BinaryField(),
        ),
    ]
