# Generated by Django 5.1.7 on 2025-03-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_patient_encrypted_insurance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='abe_policy',
            new_name='ibe_policy',
        ),
    ]
